language: node_js

node_js:
  - "0.12"
  - "0.10"
  - "iojs"
  - "iojs-v1.1.0"

# Delay to ensure mongo has started
before_script:
  - sleep 15

script:
  - "npm run cover"
  - "npm run lint"

services:
  - mongodb
